import { Piece, PieceData, Turn } from "../../types/game";
import { GameObject as GO } from "../../types/game";

export const gameObjects: GO[][] = [
	[GO.Land, GO.Land, GO.Trap, GO.End, GO.Trap, GO.Land, GO.Land],
	[GO.Land, GO.Land, GO.Land, GO.Trap, GO.Land, GO.Land, GO.Land],
	[GO.Land, GO.Land, GO.Land, GO.Land, GO.Land, GO.Land, GO.Land],
	[GO.Land, GO.Water, GO.Water, GO.Land, GO.Water, GO.Water, GO.Land],
	[GO.Land, GO.Water, GO.Water, GO.Land, GO.Water, GO.Water, GO.Land],
	[GO.Land, GO.Water, GO.Water, GO.Land, GO.Water, GO.Water, GO.Land],
	[GO.Land, GO.Land, GO.Land, GO.Land, GO.Land, GO.Land, GO.Land],
	[GO.Land, GO.Land, GO.Land, GO.Trap, GO.Land, GO.Land, GO.Land],
	[GO.Land, GO.Land, GO.Trap, GO.End, GO.Trap, GO.Land, GO.Land],
];

export const endSquares: { [key: string]: [number, number] } = {
	R: [3, 0],
	B: [3, 8],
};

export const boardState: string[][] = [
	[
		`R${Piece.Lion}`,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		`R${Piece.Tiger}`,
	],
	[
		Piece.Empty,
		`R${Piece.Dog}`,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		`R${Piece.Cat}`,
		Piece.Empty,
	],
	[
		`R${Piece.Rat}`,
		Piece.Empty,
		`R${Piece.Cheetah}`,
		Piece.Empty,
		`R${Piece.Wolf}`,
		Piece.Empty,
		`R${Piece.Elephant}`,
	],
	[
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
	],
	[
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
	],
	[
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
	],
	[
		`B${Piece.Elephant}`,
		Piece.Empty,
		`B${Piece.Wolf}`,
		Piece.Empty,
		`B${Piece.Cheetah}`,
		Piece.Empty,
		`B${Piece.Rat}`,
	],
	[
		Piece.Empty,
		`B${Piece.Cat}`,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		`B${Piece.Dog}`,
		Piece.Empty,
	],
	[
		`B${Piece.Tiger}`,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		Piece.Empty,
		`B${Piece.Lion}`,
	],
];

export const startingPieces: PieceData[] = [
	{ team: "R", name: Piece.Rat, position: [0, 2] },
	{ team: "R", name: Piece.Cat, position: [5, 1] },
	{ team: "R", name: Piece.Dog, position: [1, 1] },
	{ team: "R", name: Piece.Wolf, position: [4, 2] },
	{ team: "R", name: Piece.Cheetah, position: [2, 2] },
	{ team: "R", name: Piece.Tiger, position: [6, 0] },
	{ team: "R", name: Piece.Lion, position: [0, 0] },
	{ team: "R", name: Piece.Elephant, position: [6, 2] },
	{ team: "B", name: Piece.Rat, position: [6, 6] },
	{ team: "B", name: Piece.Cat, position: [1, 7] },
	{ team: "B", name: Piece.Dog, position: [5, 7] },
	{ team: "B", name: Piece.Wolf, position: [2, 6] },
	{ team: "B", name: Piece.Cheetah, position: [4, 6] },
	{ team: "B", name: Piece.Tiger, position: [0, 8] },
	{ team: "B", name: Piece.Lion, position: [6, 8] },
	{ team: "B", name: Piece.Elephant, position: [0, 6] },
];
